services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Kematjaya\ImportBundle\Manager\ImportManagerInterface:
        class: Kematjaya\ImportBundle\Manager\ImportManager
